/*
 * MiddlePanel.java
 *
 * Created on May 31, 2007, 12:31 PM
 */

package keno;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author David Souther
 */
public class MiddlePanel extends javax.swing.JPanel {

    ImageIcon[] marked, hit;
    ImageIcon markedIcon, hitIcon;
    View control;

    /** Creates new form MiddlePanel */
    public MiddlePanel(View c) {
        control = c;
        marked = new ImageIcon[11];
        hit = new ImageIcon[11];
        URL p, o;
        p = MiddlePanel.class.getResource("statusPanel/marked.gif");
        o = MiddlePanel.class.getResource("statusPanel/hit.gif");
        if (p != null)
            markedIcon = new ImageIcon(p);
        if (o != null)
            hitIcon = new ImageIcon(o);
        for (int i = 0; i <= 10; i++) {
            p = MiddlePanel.class.getResource("statusPanel/m_" + i + ".gif");
            o = MiddlePanel.class.getResource("statusPanel/h_" + i + ".gif");
            if (p != null)
                marked[i] = new ImageIcon(p);
            if (o != null)
                hit[i] = new ImageIcon(o);
        }

        markedNameLabel = new javax.swing.JLabel();
        markedLabel = new javax.swing.JLabel();
        hitNameLabel = new javax.swing.JLabel();
        hitLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 80));
        markedNameLabel.setIcon(markedIcon);
        markedNameLabel.setPreferredSize(new java.awt.Dimension(130, 80));

        markedLabel.setIcon(marked[0]);
        markedLabel.setPreferredSize(new java.awt.Dimension(65, 80));

        hitNameLabel.setIcon(hitIcon);
        hitNameLabel.setPreferredSize(new java.awt.Dimension(380, 80));

        hitLabel.setIcon(hit[0]);
        hitLabel.setPreferredSize(new java.awt.Dimension(75, 80));

        this.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        this.add(markedNameLabel);
        this.add(markedLabel);
        this.add(hitNameLabel);
        this.add(hitLabel);
    }

    public void setHit(int n) {
        if (n >= 0 && n <= 10)
            hitLabel.setIcon(hit[n]);
    }

    public void setMarked(int n) {
        if (n >= 0 && n <= 10)
            markedLabel.setIcon(marked[n]);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">//GEN-BEGIN:initComponents
    private void initComponents() {
        markedNameLabel = new javax.swing.JLabel();
        markedLabel = new javax.swing.JLabel();
        hitNameLabel = new javax.swing.JLabel();
        hitLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 80));
        markedNameLabel.setIcon(markedIcon);
        markedNameLabel.setPreferredSize(new java.awt.Dimension(130, 80));

        markedLabel.setIcon(marked[0]);
        markedLabel.setPreferredSize(new java.awt.Dimension(65, 80));

        hitNameLabel.setIcon(hitIcon);
        hitNameLabel.setPreferredSize(new java.awt.Dimension(380, 80));

        hitLabel.setIcon(hit[0]);
        hitLabel.setPreferredSize(new java.awt.Dimension(75, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(markedNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(markedLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hitNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hitLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(markedNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(markedLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hitNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hitLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hitLabel;
    private javax.swing.JLabel hitNameLabel;
    private javax.swing.JLabel markedLabel;
    private javax.swing.JLabel markedNameLabel;
    // End of variables declaration//GEN-END:variables

}
