/*
 * StatsPanel.java
 *
 * Created on May 27, 2007, 10:14 AM
 */

package keno;

/**
 *
 * @author David Souther
 */
public class StatsPanel extends javax.swing.JPanel {

    private View control;

    /** Creates new form StatsPanel */
    public StatsPanel(View c) {
        initComponents();
        control = c;
    }

    public int getSpeed() {
        return (Integer) SpeedSpinner.getValue();
    }

    public int getBet() {
        return (Integer) BetSpinner.getValue();
    }

    public void setPayout(int n) {
        PayoutLabel.setText("" + n);
    }

    public void setGames(int n) {
        GamesLabel.setText("" + n);
    }

    public void setCredits(int n) {
        CreditsLabel.setText("$" + n);
    }

    public void setBonus(int n) {
        BonusLabel.setText("" + n);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">//GEN-BEGIN:initComponents
    private void initComponents() {
        BetLabelName = new javax.swing.JLabel();
        BetSpinner = new javax.swing.JSpinner();
        PayoutLabelName = new javax.swing.JLabel();
        PayoutLabel = new javax.swing.JLabel();
        GamesLabelName = new javax.swing.JLabel();
        CreditsLabelName = new javax.swing.JLabel();
        GamesLabel = new javax.swing.JLabel();
        CreditsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ClearButton = new javax.swing.JButton();
        RandomButton = new javax.swing.JButton();
        CreditsSpinner = new javax.swing.JSpinner();
        AddCreditsButton = new javax.swing.JButton();
        BonusLabel = new javax.swing.JLabel();
        BonusNameLabel = new javax.swing.JLabel();
        SpeedNameLabel = new javax.swing.JLabel();
        SpeedSpinner = new javax.swing.JSpinner();

        BetLabelName.setText("Bet:");

        BetSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        PayoutLabelName.setText("Payout:");

        PayoutLabel.setText("0");

        GamesLabelName.setText("Games:");

        CreditsLabelName.setText("Credits:");

        GamesLabel.setText("0");

        CreditsLabel.setText("0");

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        RandomButton.setText("Random");
        RandomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomButtonActionPerformed(evt);
            }
        });

        CreditsSpinner.setModel(new javax.swing.SpinnerNumberModel(100, 0, 1000, 5));

        AddCreditsButton.setText("Add $$");
        AddCreditsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCreditsButtonActionPerformed(evt);
            }
        });

        BonusLabel.setText("0");

        BonusNameLabel.setText("Bonus:");

        SpeedNameLabel.setText("Speed:");

        SpeedSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 1, 5, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addComponent(ClearButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21,
                                                        Short.MAX_VALUE)
                                                .addComponent(RandomButton))
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 149,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(SpeedNameLabel)
                                                        .addComponent(GamesLabelName)
                                                        .addComponent(CreditsLabelName)
                                                        .addComponent(CreditsSpinner,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24,
                                                        Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(CreditsLabel)
                                                        .addComponent(GamesLabel)
                                                        .addComponent(SpeedSpinner,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(AddCreditsButton)))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 149,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(BonusNameLabel)
                                                        .addComponent(BetLabelName)
                                                        .addComponent(PayoutLabelName))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82,
                                                        Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(BonusLabel,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(BetSpinner,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PayoutLabel,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(BonusNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BetLabelName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(PayoutLabelName)
                                                .addGap(12, 12, 12))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(BonusLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(PayoutLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(SpeedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(GamesLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CreditsLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddCreditsButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(SpeedNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(GamesLabelName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CreditsLabelName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CreditsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ClearButton)
                                        .addComponent(RandomButton))
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void AddCreditsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddCreditsButtonActionPerformed
        control.addCredits((Integer) CreditsSpinner.getValue());
    }// GEN-LAST:event_AddCreditsButtonActionPerformed

    private void RandomButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RandomButtonActionPerformed
        control.random();
    }// GEN-LAST:event_RandomButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ClearButtonActionPerformed
        control.clear();
    }// GEN-LAST:event_ClearButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCreditsButton;
    private javax.swing.JLabel BetLabelName;
    private javax.swing.JSpinner BetSpinner;
    private javax.swing.JLabel BonusLabel;
    private javax.swing.JLabel BonusNameLabel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel CreditsLabel;
    private javax.swing.JLabel CreditsLabelName;
    private javax.swing.JSpinner CreditsSpinner;
    private javax.swing.JLabel GamesLabel;
    private javax.swing.JLabel GamesLabelName;
    private javax.swing.JLabel PayoutLabel;
    private javax.swing.JLabel PayoutLabelName;
    private javax.swing.JButton RandomButton;
    private javax.swing.JLabel SpeedNameLabel;
    private javax.swing.JSpinner SpeedSpinner;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
